/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iot_catalogue.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IoTComponent service. Represents a row in the &quot;IoTCatalogue_IoTComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.iot_catalogue.model.impl.IoTComponentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.iot_catalogue.model.impl.IoTComponentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IoTComponent
 * @generated
 */
@ProviderType
public interface IoTComponentModel
	extends BaseModel<IoTComponent>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a io t component model instance should use the {@link IoTComponent} interface instead.
	 */

	/**
	 * Returns the primary key of this io t component.
	 *
	 * @return the primary key of this io t component
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this io t component.
	 *
	 * @param primaryKey the primary key of this io t component
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this io t component.
	 *
	 * @return the uuid of this io t component
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this io t component.
	 *
	 * @param uuid the uuid of this io t component
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the iot component ID of this io t component.
	 *
	 * @return the iot component ID of this io t component
	 */
	public long getIotComponentId();

	/**
	 * Sets the iot component ID of this io t component.
	 *
	 * @param iotComponentId the iot component ID of this io t component
	 */
	public void setIotComponentId(long iotComponentId);

	/**
	 * Returns the group ID of this io t component.
	 *
	 * @return the group ID of this io t component
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this io t component.
	 *
	 * @param groupId the group ID of this io t component
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this io t component.
	 *
	 * @return the company ID of this io t component
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this io t component.
	 *
	 * @param companyId the company ID of this io t component
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this io t component.
	 *
	 * @return the user ID of this io t component
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this io t component.
	 *
	 * @param userId the user ID of this io t component
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this io t component.
	 *
	 * @return the user uuid of this io t component
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this io t component.
	 *
	 * @param userUuid the user uuid of this io t component
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this io t component.
	 *
	 * @return the user name of this io t component
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this io t component.
	 *
	 * @param userName the user name of this io t component
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this io t component.
	 *
	 * @return the create date of this io t component
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this io t component.
	 *
	 * @param createDate the create date of this io t component
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this io t component.
	 *
	 * @return the modified date of this io t component
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this io t component.
	 *
	 * @param modifiedDate the modified date of this io t component
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this io t component.
	 *
	 * @return the status of this io t component
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this io t component.
	 *
	 * @param status the status of this io t component
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this io t component.
	 *
	 * @return the status by user ID of this io t component
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this io t component.
	 *
	 * @param statusByUserId the status by user ID of this io t component
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this io t component.
	 *
	 * @return the status by user uuid of this io t component
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this io t component.
	 *
	 * @param statusByUserUuid the status by user uuid of this io t component
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this io t component.
	 *
	 * @return the status by user name of this io t component
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this io t component.
	 *
	 * @param statusByUserName the status by user name of this io t component
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this io t component.
	 *
	 * @return the status date of this io t component
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this io t component.
	 *
	 * @param statusDate the status date of this io t component
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the original ID of this io t component.
	 *
	 * @return the original ID of this io t component
	 */
	@AutoEscape
	public String getOriginalId();

	/**
	 * Sets the original ID of this io t component.
	 *
	 * @param originalId the original ID of this io t component
	 */
	public void setOriginalId(String originalId);

	/**
	 * Returns the name of this io t component.
	 *
	 * @return the name of this io t component
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this io t component.
	 *
	 * @param name the name of this io t component
	 */
	public void setName(String name);

	/**
	 * Returns the description of this io t component.
	 *
	 * @return the description of this io t component
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this io t component.
	 *
	 * @param description the description of this io t component
	 */
	public void setDescription(String description);

	/**
	 * Returns the embedded url of this io t component.
	 *
	 * @return the embedded url of this io t component
	 */
	@AutoEscape
	public String getEmbeddedUrl();

	/**
	 * Sets the embedded url of this io t component.
	 *
	 * @param embeddedUrl the embedded url of this io t component
	 */
	public void setEmbeddedUrl(String embeddedUrl);

	/**
	 * Returns the image url of this io t component.
	 *
	 * @return the image url of this io t component
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this io t component.
	 *
	 * @param imageUrl the image url of this io t component
	 */
	public void setImageUrl(String imageUrl);

	/**
	 * Returns the element status of this io t component.
	 *
	 * @return the element status of this io t component
	 */
	@AutoEscape
	public String getElementStatus();

	/**
	 * Sets the element status of this io t component.
	 *
	 * @param elementStatus the element status of this io t component
	 */
	public void setElementStatus(String elementStatus);

	/**
	 * Returns the subscription ID of this io t component.
	 *
	 * @return the subscription ID of this io t component
	 */
	public long getSubscriptionId();

	/**
	 * Sets the subscription ID of this io t component.
	 *
	 * @param subscriptionId the subscription ID of this io t component
	 */
	public void setSubscriptionId(long subscriptionId);

	/**
	 * Returns <code>true</code> if this io t component is approved.
	 *
	 * @return <code>true</code> if this io t component is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this io t component is denied.
	 *
	 * @return <code>true</code> if this io t component is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this io t component is a draft.
	 *
	 * @return <code>true</code> if this io t component is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this io t component is expired.
	 *
	 * @return <code>true</code> if this io t component is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this io t component is inactive.
	 *
	 * @return <code>true</code> if this io t component is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this io t component is incomplete.
	 *
	 * @return <code>true</code> if this io t component is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this io t component is pending.
	 *
	 * @return <code>true</code> if this io t component is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this io t component is scheduled.
	 *
	 * @return <code>true</code> if this io t component is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}