/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iot_catalogue.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Subscription service. Represents a row in the &quot;IoTCatalogue_Subscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.iot_catalogue.model.impl.SubscriptionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.iot_catalogue.model.impl.SubscriptionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Subscription
 * @generated
 */
@ProviderType
public interface SubscriptionModel
	extends BaseModel<Subscription>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subscription model instance should use the {@link Subscription} interface instead.
	 */

	/**
	 * Returns the primary key of this subscription.
	 *
	 * @return the primary key of this subscription
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subscription.
	 *
	 * @param primaryKey the primary key of this subscription
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this subscription.
	 *
	 * @return the uuid of this subscription
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this subscription.
	 *
	 * @param uuid the uuid of this subscription
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the subscription ID of this subscription.
	 *
	 * @return the subscription ID of this subscription
	 */
	public long getSubscriptionId();

	/**
	 * Sets the subscription ID of this subscription.
	 *
	 * @param subscriptionId the subscription ID of this subscription
	 */
	public void setSubscriptionId(long subscriptionId);

	/**
	 * Returns the group ID of this subscription.
	 *
	 * @return the group ID of this subscription
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this subscription.
	 *
	 * @param groupId the group ID of this subscription
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this subscription.
	 *
	 * @return the company ID of this subscription
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this subscription.
	 *
	 * @param companyId the company ID of this subscription
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this subscription.
	 *
	 * @return the user ID of this subscription
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this subscription.
	 *
	 * @param userId the user ID of this subscription
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this subscription.
	 *
	 * @return the user uuid of this subscription
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this subscription.
	 *
	 * @param userUuid the user uuid of this subscription
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this subscription.
	 *
	 * @return the user name of this subscription
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this subscription.
	 *
	 * @param userName the user name of this subscription
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this subscription.
	 *
	 * @return the create date of this subscription
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this subscription.
	 *
	 * @param createDate the create date of this subscription
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this subscription.
	 *
	 * @return the modified date of this subscription
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this subscription.
	 *
	 * @param modifiedDate the modified date of this subscription
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this subscription.
	 *
	 * @return the status of this subscription
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this subscription.
	 *
	 * @param status the status of this subscription
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this subscription.
	 *
	 * @return the status by user ID of this subscription
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this subscription.
	 *
	 * @param statusByUserId the status by user ID of this subscription
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this subscription.
	 *
	 * @return the status by user uuid of this subscription
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this subscription.
	 *
	 * @param statusByUserUuid the status by user uuid of this subscription
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this subscription.
	 *
	 * @return the status by user name of this subscription
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this subscription.
	 *
	 * @param statusByUserName the status by user name of this subscription
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this subscription.
	 *
	 * @return the status date of this subscription
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this subscription.
	 *
	 * @param statusDate the status date of this subscription
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the connection ID of this subscription.
	 *
	 * @return the connection ID of this subscription
	 */
	@AutoEscape
	public String getConnectionId();

	/**
	 * Sets the connection ID of this subscription.
	 *
	 * @param connectionId the connection ID of this subscription
	 */
	public void setConnectionId(String connectionId);

	/**
	 * Returns the connection state of this subscription.
	 *
	 * @return the connection state of this subscription
	 */
	@AutoEscape
	public String getConnectionState();

	/**
	 * Sets the connection state of this subscription.
	 *
	 * @param connectionState the connection state of this subscription
	 */
	public void setConnectionState(String connectionState);

	/**
	 * Returns the token of this subscription.
	 *
	 * @return the token of this subscription
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this subscription.
	 *
	 * @param token the token of this subscription
	 */
	public void setToken(String token);

	/**
	 * Returns the socket address of this subscription.
	 *
	 * @return the socket address of this subscription
	 */
	@AutoEscape
	public String getSocketAddress();

	/**
	 * Sets the socket address of this subscription.
	 *
	 * @param socketAddress the socket address of this subscription
	 */
	public void setSocketAddress(String socketAddress);

	/**
	 * Returns <code>true</code> if this subscription is approved.
	 *
	 * @return <code>true</code> if this subscription is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this subscription is denied.
	 *
	 * @return <code>true</code> if this subscription is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this subscription is a draft.
	 *
	 * @return <code>true</code> if this subscription is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this subscription is expired.
	 *
	 * @return <code>true</code> if this subscription is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this subscription is inactive.
	 *
	 * @return <code>true</code> if this subscription is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this subscription is incomplete.
	 *
	 * @return <code>true</code> if this subscription is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this subscription is pending.
	 *
	 * @return <code>true</code> if this subscription is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this subscription is scheduled.
	 *
	 * @return <code>true</code> if this subscription is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}