/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iot_catalogue.model.impl;

import com.iot_catalogue.model.ElementCoordinate;
import com.iot_catalogue.model.ElementCoordinateModel;
import com.iot_catalogue.model.ElementCoordinateSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ElementCoordinate service. Represents a row in the &quot;IoTCatalogue_ElementCoordinate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ElementCoordinateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ElementCoordinateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElementCoordinateImpl
 * @generated
 */
@JSON(strict = true)
public class ElementCoordinateModelImpl
	extends BaseModelImpl<ElementCoordinate> implements ElementCoordinateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a element coordinate model instance should use the <code>ElementCoordinate</code> interface instead.
	 */
	public static final String TABLE_NAME = "IoTCatalogue_ElementCoordinate";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"elementCoordinateId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"elementOriginalId", Types.VARCHAR},
		{"elementClassName", Types.VARCHAR}, {"latitude", Types.DOUBLE},
		{"longitude", Types.DOUBLE}, {"subscriptionId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("elementCoordinateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("elementOriginalId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("elementClassName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("subscriptionId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table IoTCatalogue_ElementCoordinate (uuid_ VARCHAR(75) null,elementCoordinateId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,elementOriginalId VARCHAR(75) null,elementClassName VARCHAR(75) null,latitude DOUBLE,longitude DOUBLE,subscriptionId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table IoTCatalogue_ElementCoordinate";

	public static final String ORDER_BY_JPQL =
		" ORDER BY elementCoordinate.elementCoordinateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY IoTCatalogue_ElementCoordinate.elementCoordinateId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ELEMENTCLASSNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ELEMENTORIGINALID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBSCRIPTIONID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ELEMENTCOORDINATEID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ElementCoordinate toModel(ElementCoordinateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ElementCoordinate model = new ElementCoordinateImpl();

		model.setUuid(soapModel.getUuid());
		model.setElementCoordinateId(soapModel.getElementCoordinateId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setElementOriginalId(soapModel.getElementOriginalId());
		model.setElementClassName(soapModel.getElementClassName());
		model.setLatitude(soapModel.getLatitude());
		model.setLongitude(soapModel.getLongitude());
		model.setSubscriptionId(soapModel.getSubscriptionId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ElementCoordinate> toModels(
		ElementCoordinateSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ElementCoordinate> models = new ArrayList<ElementCoordinate>(
			soapModels.length);

		for (ElementCoordinateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ElementCoordinateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _elementCoordinateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setElementCoordinateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _elementCoordinateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ElementCoordinate.class;
	}

	@Override
	public String getModelClassName() {
		return ElementCoordinate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ElementCoordinate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ElementCoordinate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ElementCoordinate, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ElementCoordinate)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ElementCoordinate, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ElementCoordinate, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ElementCoordinate)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ElementCoordinate, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ElementCoordinate, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ElementCoordinate>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ElementCoordinate.class.getClassLoader(), ElementCoordinate.class,
			ModelWrapper.class);

		try {
			Constructor<ElementCoordinate> constructor =
				(Constructor<ElementCoordinate>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ElementCoordinate, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ElementCoordinate, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ElementCoordinate, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ElementCoordinate, Object>>();
		Map<String, BiConsumer<ElementCoordinate, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ElementCoordinate, ?>>();

		attributeGetterFunctions.put("uuid", ElementCoordinate::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ElementCoordinate, String>)ElementCoordinate::setUuid);
		attributeGetterFunctions.put(
			"elementCoordinateId", ElementCoordinate::getElementCoordinateId);
		attributeSetterBiConsumers.put(
			"elementCoordinateId",
			(BiConsumer<ElementCoordinate, Long>)
				ElementCoordinate::setElementCoordinateId);
		attributeGetterFunctions.put("groupId", ElementCoordinate::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ElementCoordinate, Long>)ElementCoordinate::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ElementCoordinate::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ElementCoordinate, Long>)
				ElementCoordinate::setCompanyId);
		attributeGetterFunctions.put("userId", ElementCoordinate::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ElementCoordinate, Long>)ElementCoordinate::setUserId);
		attributeGetterFunctions.put(
			"userName", ElementCoordinate::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ElementCoordinate, String>)
				ElementCoordinate::setUserName);
		attributeGetterFunctions.put(
			"createDate", ElementCoordinate::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ElementCoordinate, Date>)
				ElementCoordinate::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ElementCoordinate::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ElementCoordinate, Date>)
				ElementCoordinate::setModifiedDate);
		attributeGetterFunctions.put("status", ElementCoordinate::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<ElementCoordinate, Integer>)
				ElementCoordinate::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", ElementCoordinate::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<ElementCoordinate, Long>)
				ElementCoordinate::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", ElementCoordinate::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<ElementCoordinate, String>)
				ElementCoordinate::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", ElementCoordinate::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<ElementCoordinate, Date>)
				ElementCoordinate::setStatusDate);
		attributeGetterFunctions.put(
			"elementOriginalId", ElementCoordinate::getElementOriginalId);
		attributeSetterBiConsumers.put(
			"elementOriginalId",
			(BiConsumer<ElementCoordinate, String>)
				ElementCoordinate::setElementOriginalId);
		attributeGetterFunctions.put(
			"elementClassName", ElementCoordinate::getElementClassName);
		attributeSetterBiConsumers.put(
			"elementClassName",
			(BiConsumer<ElementCoordinate, String>)
				ElementCoordinate::setElementClassName);
		attributeGetterFunctions.put(
			"latitude", ElementCoordinate::getLatitude);
		attributeSetterBiConsumers.put(
			"latitude",
			(BiConsumer<ElementCoordinate, Double>)
				ElementCoordinate::setLatitude);
		attributeGetterFunctions.put(
			"longitude", ElementCoordinate::getLongitude);
		attributeSetterBiConsumers.put(
			"longitude",
			(BiConsumer<ElementCoordinate, Double>)
				ElementCoordinate::setLongitude);
		attributeGetterFunctions.put(
			"subscriptionId", ElementCoordinate::getSubscriptionId);
		attributeSetterBiConsumers.put(
			"subscriptionId",
			(BiConsumer<ElementCoordinate, Long>)
				ElementCoordinate::setSubscriptionId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getElementCoordinateId() {
		return _elementCoordinateId;
	}

	@Override
	public void setElementCoordinateId(long elementCoordinateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_elementCoordinateId = elementCoordinateId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getElementOriginalId() {
		if (_elementOriginalId == null) {
			return "";
		}
		else {
			return _elementOriginalId;
		}
	}

	@Override
	public void setElementOriginalId(String elementOriginalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_elementOriginalId = elementOriginalId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalElementOriginalId() {
		return getColumnOriginalValue("elementOriginalId");
	}

	@JSON
	@Override
	public String getElementClassName() {
		if (_elementClassName == null) {
			return "";
		}
		else {
			return _elementClassName;
		}
	}

	@Override
	public void setElementClassName(String elementClassName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_elementClassName = elementClassName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalElementClassName() {
		return getColumnOriginalValue("elementClassName");
	}

	@JSON
	@Override
	public double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(double latitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_latitude = latitude;
	}

	@JSON
	@Override
	public double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(double longitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_longitude = longitude;
	}

	@JSON
	@Override
	public long getSubscriptionId() {
		return _subscriptionId;
	}

	@Override
	public void setSubscriptionId(long subscriptionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subscriptionId = subscriptionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSubscriptionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("subscriptionId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ElementCoordinate.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ElementCoordinate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ElementCoordinate toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ElementCoordinate>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ElementCoordinateImpl elementCoordinateImpl =
			new ElementCoordinateImpl();

		elementCoordinateImpl.setUuid(getUuid());
		elementCoordinateImpl.setElementCoordinateId(getElementCoordinateId());
		elementCoordinateImpl.setGroupId(getGroupId());
		elementCoordinateImpl.setCompanyId(getCompanyId());
		elementCoordinateImpl.setUserId(getUserId());
		elementCoordinateImpl.setUserName(getUserName());
		elementCoordinateImpl.setCreateDate(getCreateDate());
		elementCoordinateImpl.setModifiedDate(getModifiedDate());
		elementCoordinateImpl.setStatus(getStatus());
		elementCoordinateImpl.setStatusByUserId(getStatusByUserId());
		elementCoordinateImpl.setStatusByUserName(getStatusByUserName());
		elementCoordinateImpl.setStatusDate(getStatusDate());
		elementCoordinateImpl.setElementOriginalId(getElementOriginalId());
		elementCoordinateImpl.setElementClassName(getElementClassName());
		elementCoordinateImpl.setLatitude(getLatitude());
		elementCoordinateImpl.setLongitude(getLongitude());
		elementCoordinateImpl.setSubscriptionId(getSubscriptionId());

		elementCoordinateImpl.resetOriginalValues();

		return elementCoordinateImpl;
	}

	@Override
	public int compareTo(ElementCoordinate elementCoordinate) {
		long primaryKey = elementCoordinate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ElementCoordinate)) {
			return false;
		}

		ElementCoordinate elementCoordinate = (ElementCoordinate)object;

		long primaryKey = elementCoordinate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ElementCoordinate> toCacheModel() {
		ElementCoordinateCacheModel elementCoordinateCacheModel =
			new ElementCoordinateCacheModel();

		elementCoordinateCacheModel.uuid = getUuid();

		String uuid = elementCoordinateCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			elementCoordinateCacheModel.uuid = null;
		}

		elementCoordinateCacheModel.elementCoordinateId =
			getElementCoordinateId();

		elementCoordinateCacheModel.groupId = getGroupId();

		elementCoordinateCacheModel.companyId = getCompanyId();

		elementCoordinateCacheModel.userId = getUserId();

		elementCoordinateCacheModel.userName = getUserName();

		String userName = elementCoordinateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			elementCoordinateCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			elementCoordinateCacheModel.createDate = createDate.getTime();
		}
		else {
			elementCoordinateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			elementCoordinateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			elementCoordinateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		elementCoordinateCacheModel.status = getStatus();

		elementCoordinateCacheModel.statusByUserId = getStatusByUserId();

		elementCoordinateCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = elementCoordinateCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			elementCoordinateCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			elementCoordinateCacheModel.statusDate = statusDate.getTime();
		}
		else {
			elementCoordinateCacheModel.statusDate = Long.MIN_VALUE;
		}

		elementCoordinateCacheModel.elementOriginalId = getElementOriginalId();

		String elementOriginalId =
			elementCoordinateCacheModel.elementOriginalId;

		if ((elementOriginalId != null) && (elementOriginalId.length() == 0)) {
			elementCoordinateCacheModel.elementOriginalId = null;
		}

		elementCoordinateCacheModel.elementClassName = getElementClassName();

		String elementClassName = elementCoordinateCacheModel.elementClassName;

		if ((elementClassName != null) && (elementClassName.length() == 0)) {
			elementCoordinateCacheModel.elementClassName = null;
		}

		elementCoordinateCacheModel.latitude = getLatitude();

		elementCoordinateCacheModel.longitude = getLongitude();

		elementCoordinateCacheModel.subscriptionId = getSubscriptionId();

		return elementCoordinateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ElementCoordinate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ElementCoordinate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ElementCoordinate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ElementCoordinate)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ElementCoordinate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ElementCoordinate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ElementCoordinate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ElementCoordinate)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ElementCoordinate>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _elementCoordinateId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _elementOriginalId;
	private String _elementClassName;
	private double _latitude;
	private double _longitude;
	private long _subscriptionId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ElementCoordinate, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ElementCoordinate)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("elementCoordinateId", _elementCoordinateId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("elementOriginalId", _elementOriginalId);
		_columnOriginalValues.put("elementClassName", _elementClassName);
		_columnOriginalValues.put("latitude", _latitude);
		_columnOriginalValues.put("longitude", _longitude);
		_columnOriginalValues.put("subscriptionId", _subscriptionId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("elementCoordinateId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("elementOriginalId", 4096L);

		columnBitmasks.put("elementClassName", 8192L);

		columnBitmasks.put("latitude", 16384L);

		columnBitmasks.put("longitude", 32768L);

		columnBitmasks.put("subscriptionId", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ElementCoordinate _escapedModel;

}