/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iot_catalogue.model.impl;

import com.iot_catalogue.model.IoTComponent;
import com.iot_catalogue.model.IoTComponentModel;
import com.iot_catalogue.model.IoTComponentSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the IoTComponent service. Represents a row in the &quot;IoTCatalogue_IoTComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>IoTComponentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IoTComponentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IoTComponentImpl
 * @generated
 */
@JSON(strict = true)
public class IoTComponentModelImpl
	extends BaseModelImpl<IoTComponent> implements IoTComponentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a io t component model instance should use the <code>IoTComponent</code> interface instead.
	 */
	public static final String TABLE_NAME = "IoTCatalogue_IoTComponent";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"iotComponentId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"originalId", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"embeddedUrl", Types.VARCHAR},
		{"imageUrl", Types.VARCHAR}, {"elementStatus", Types.VARCHAR},
		{"subscriptionId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("iotComponentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("originalId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("embeddedUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("elementStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subscriptionId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table IoTCatalogue_IoTComponent (uuid_ VARCHAR(75) null,iotComponentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,originalId VARCHAR(75) null,name VARCHAR(1000) null,description TEXT null,embeddedUrl VARCHAR(2000) null,imageUrl VARCHAR(500) null,elementStatus VARCHAR(75) null,subscriptionId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table IoTCatalogue_IoTComponent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ioTComponent.iotComponentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY IoTCatalogue_IoTComponent.iotComponentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORIGINALID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBSCRIPTIONID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IOTCOMPONENTID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static IoTComponent toModel(IoTComponentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		IoTComponent model = new IoTComponentImpl();

		model.setUuid(soapModel.getUuid());
		model.setIotComponentId(soapModel.getIotComponentId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setOriginalId(soapModel.getOriginalId());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setEmbeddedUrl(soapModel.getEmbeddedUrl());
		model.setImageUrl(soapModel.getImageUrl());
		model.setElementStatus(soapModel.getElementStatus());
		model.setSubscriptionId(soapModel.getSubscriptionId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<IoTComponent> toModels(IoTComponentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<IoTComponent> models = new ArrayList<IoTComponent>(
			soapModels.length);

		for (IoTComponentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public IoTComponentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _iotComponentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIotComponentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _iotComponentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return IoTComponent.class;
	}

	@Override
	public String getModelClassName() {
		return IoTComponent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<IoTComponent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<IoTComponent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IoTComponent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((IoTComponent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<IoTComponent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<IoTComponent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(IoTComponent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<IoTComponent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<IoTComponent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, IoTComponent>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			IoTComponent.class.getClassLoader(), IoTComponent.class,
			ModelWrapper.class);

		try {
			Constructor<IoTComponent> constructor =
				(Constructor<IoTComponent>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<IoTComponent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<IoTComponent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<IoTComponent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<IoTComponent, Object>>();
		Map<String, BiConsumer<IoTComponent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<IoTComponent, ?>>();

		attributeGetterFunctions.put("uuid", IoTComponent::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<IoTComponent, String>)IoTComponent::setUuid);
		attributeGetterFunctions.put(
			"iotComponentId", IoTComponent::getIotComponentId);
		attributeSetterBiConsumers.put(
			"iotComponentId",
			(BiConsumer<IoTComponent, Long>)IoTComponent::setIotComponentId);
		attributeGetterFunctions.put("groupId", IoTComponent::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<IoTComponent, Long>)IoTComponent::setGroupId);
		attributeGetterFunctions.put("companyId", IoTComponent::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<IoTComponent, Long>)IoTComponent::setCompanyId);
		attributeGetterFunctions.put("userId", IoTComponent::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<IoTComponent, Long>)IoTComponent::setUserId);
		attributeGetterFunctions.put("userName", IoTComponent::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<IoTComponent, String>)IoTComponent::setUserName);
		attributeGetterFunctions.put("createDate", IoTComponent::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<IoTComponent, Date>)IoTComponent::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", IoTComponent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<IoTComponent, Date>)IoTComponent::setModifiedDate);
		attributeGetterFunctions.put("status", IoTComponent::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<IoTComponent, Integer>)IoTComponent::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", IoTComponent::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<IoTComponent, Long>)IoTComponent::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", IoTComponent::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<IoTComponent, String>)
				IoTComponent::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", IoTComponent::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<IoTComponent, Date>)IoTComponent::setStatusDate);
		attributeGetterFunctions.put("originalId", IoTComponent::getOriginalId);
		attributeSetterBiConsumers.put(
			"originalId",
			(BiConsumer<IoTComponent, String>)IoTComponent::setOriginalId);
		attributeGetterFunctions.put("name", IoTComponent::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<IoTComponent, String>)IoTComponent::setName);
		attributeGetterFunctions.put(
			"description", IoTComponent::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<IoTComponent, String>)IoTComponent::setDescription);
		attributeGetterFunctions.put(
			"embeddedUrl", IoTComponent::getEmbeddedUrl);
		attributeSetterBiConsumers.put(
			"embeddedUrl",
			(BiConsumer<IoTComponent, String>)IoTComponent::setEmbeddedUrl);
		attributeGetterFunctions.put("imageUrl", IoTComponent::getImageUrl);
		attributeSetterBiConsumers.put(
			"imageUrl",
			(BiConsumer<IoTComponent, String>)IoTComponent::setImageUrl);
		attributeGetterFunctions.put(
			"elementStatus", IoTComponent::getElementStatus);
		attributeSetterBiConsumers.put(
			"elementStatus",
			(BiConsumer<IoTComponent, String>)IoTComponent::setElementStatus);
		attributeGetterFunctions.put(
			"subscriptionId", IoTComponent::getSubscriptionId);
		attributeSetterBiConsumers.put(
			"subscriptionId",
			(BiConsumer<IoTComponent, Long>)IoTComponent::setSubscriptionId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getIotComponentId() {
		return _iotComponentId;
	}

	@Override
	public void setIotComponentId(long iotComponentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iotComponentId = iotComponentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getOriginalId() {
		if (_originalId == null) {
			return "";
		}
		else {
			return _originalId;
		}
	}

	@Override
	public void setOriginalId(String originalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalId = originalId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalOriginalId() {
		return getColumnOriginalValue("originalId");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getEmbeddedUrl() {
		if (_embeddedUrl == null) {
			return "";
		}
		else {
			return _embeddedUrl;
		}
	}

	@Override
	public void setEmbeddedUrl(String embeddedUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_embeddedUrl = embeddedUrl;
	}

	@JSON
	@Override
	public String getImageUrl() {
		if (_imageUrl == null) {
			return "";
		}
		else {
			return _imageUrl;
		}
	}

	@Override
	public void setImageUrl(String imageUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageUrl = imageUrl;
	}

	@JSON
	@Override
	public String getElementStatus() {
		if (_elementStatus == null) {
			return "";
		}
		else {
			return _elementStatus;
		}
	}

	@Override
	public void setElementStatus(String elementStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_elementStatus = elementStatus;
	}

	@JSON
	@Override
	public long getSubscriptionId() {
		return _subscriptionId;
	}

	@Override
	public void setSubscriptionId(long subscriptionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subscriptionId = subscriptionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSubscriptionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("subscriptionId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(IoTComponent.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), IoTComponent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public IoTComponent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, IoTComponent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		IoTComponentImpl ioTComponentImpl = new IoTComponentImpl();

		ioTComponentImpl.setUuid(getUuid());
		ioTComponentImpl.setIotComponentId(getIotComponentId());
		ioTComponentImpl.setGroupId(getGroupId());
		ioTComponentImpl.setCompanyId(getCompanyId());
		ioTComponentImpl.setUserId(getUserId());
		ioTComponentImpl.setUserName(getUserName());
		ioTComponentImpl.setCreateDate(getCreateDate());
		ioTComponentImpl.setModifiedDate(getModifiedDate());
		ioTComponentImpl.setStatus(getStatus());
		ioTComponentImpl.setStatusByUserId(getStatusByUserId());
		ioTComponentImpl.setStatusByUserName(getStatusByUserName());
		ioTComponentImpl.setStatusDate(getStatusDate());
		ioTComponentImpl.setOriginalId(getOriginalId());
		ioTComponentImpl.setName(getName());
		ioTComponentImpl.setDescription(getDescription());
		ioTComponentImpl.setEmbeddedUrl(getEmbeddedUrl());
		ioTComponentImpl.setImageUrl(getImageUrl());
		ioTComponentImpl.setElementStatus(getElementStatus());
		ioTComponentImpl.setSubscriptionId(getSubscriptionId());

		ioTComponentImpl.resetOriginalValues();

		return ioTComponentImpl;
	}

	@Override
	public int compareTo(IoTComponent ioTComponent) {
		long primaryKey = ioTComponent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof IoTComponent)) {
			return false;
		}

		IoTComponent ioTComponent = (IoTComponent)object;

		long primaryKey = ioTComponent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<IoTComponent> toCacheModel() {
		IoTComponentCacheModel ioTComponentCacheModel =
			new IoTComponentCacheModel();

		ioTComponentCacheModel.uuid = getUuid();

		String uuid = ioTComponentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ioTComponentCacheModel.uuid = null;
		}

		ioTComponentCacheModel.iotComponentId = getIotComponentId();

		ioTComponentCacheModel.groupId = getGroupId();

		ioTComponentCacheModel.companyId = getCompanyId();

		ioTComponentCacheModel.userId = getUserId();

		ioTComponentCacheModel.userName = getUserName();

		String userName = ioTComponentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ioTComponentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ioTComponentCacheModel.createDate = createDate.getTime();
		}
		else {
			ioTComponentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ioTComponentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ioTComponentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ioTComponentCacheModel.status = getStatus();

		ioTComponentCacheModel.statusByUserId = getStatusByUserId();

		ioTComponentCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = ioTComponentCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			ioTComponentCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			ioTComponentCacheModel.statusDate = statusDate.getTime();
		}
		else {
			ioTComponentCacheModel.statusDate = Long.MIN_VALUE;
		}

		ioTComponentCacheModel.originalId = getOriginalId();

		String originalId = ioTComponentCacheModel.originalId;

		if ((originalId != null) && (originalId.length() == 0)) {
			ioTComponentCacheModel.originalId = null;
		}

		ioTComponentCacheModel.name = getName();

		String name = ioTComponentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			ioTComponentCacheModel.name = null;
		}

		ioTComponentCacheModel.description = getDescription();

		String description = ioTComponentCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			ioTComponentCacheModel.description = null;
		}

		ioTComponentCacheModel.embeddedUrl = getEmbeddedUrl();

		String embeddedUrl = ioTComponentCacheModel.embeddedUrl;

		if ((embeddedUrl != null) && (embeddedUrl.length() == 0)) {
			ioTComponentCacheModel.embeddedUrl = null;
		}

		ioTComponentCacheModel.imageUrl = getImageUrl();

		String imageUrl = ioTComponentCacheModel.imageUrl;

		if ((imageUrl != null) && (imageUrl.length() == 0)) {
			ioTComponentCacheModel.imageUrl = null;
		}

		ioTComponentCacheModel.elementStatus = getElementStatus();

		String elementStatus = ioTComponentCacheModel.elementStatus;

		if ((elementStatus != null) && (elementStatus.length() == 0)) {
			ioTComponentCacheModel.elementStatus = null;
		}

		ioTComponentCacheModel.subscriptionId = getSubscriptionId();

		return ioTComponentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<IoTComponent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<IoTComponent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IoTComponent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((IoTComponent)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<IoTComponent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<IoTComponent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IoTComponent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((IoTComponent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, IoTComponent>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _iotComponentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _originalId;
	private String _name;
	private String _description;
	private String _embeddedUrl;
	private String _imageUrl;
	private String _elementStatus;
	private long _subscriptionId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<IoTComponent, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((IoTComponent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("iotComponentId", _iotComponentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("originalId", _originalId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("embeddedUrl", _embeddedUrl);
		_columnOriginalValues.put("imageUrl", _imageUrl);
		_columnOriginalValues.put("elementStatus", _elementStatus);
		_columnOriginalValues.put("subscriptionId", _subscriptionId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("iotComponentId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("originalId", 4096L);

		columnBitmasks.put("name", 8192L);

		columnBitmasks.put("description", 16384L);

		columnBitmasks.put("embeddedUrl", 32768L);

		columnBitmasks.put("imageUrl", 65536L);

		columnBitmasks.put("elementStatus", 131072L);

		columnBitmasks.put("subscriptionId", 262144L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private IoTComponent _escapedModel;

}